#!/usr/bin/env bash
#
# dev-setup.sh - Configure local development environment with available ports
#
# Creates:
#   backend/.env.local   - PORT=XXXX
#   frontend/.env.local  - VITE_PORT=XXXX, VITE_API_URL=http://localhost:XXXX
#
# Idempotent: re-running updates the files with new ports

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

# Get available ports
echo "🔍 Finding available ports..."
eval "$("$SCRIPT_DIR/dev-ports.sh")"

# Create backend/.env.local
BACKEND_ENV="$PROJECT_ROOT/backend/.env.local"
cat > "$BACKEND_ENV" << EOF
# Auto-generated by dev-setup.sh - do not commit
PORT=$BACKEND_PORT
EOF
echo "✅ Created $BACKEND_ENV"

# Create frontend/.env.local
FRONTEND_ENV="$PROJECT_ROOT/frontend/.env.local"
cat > "$FRONTEND_ENV" << EOF
# Auto-generated by dev-setup.sh - do not commit
VITE_PORT=$FRONTEND_PORT
VITE_API_URL=http://localhost:$BACKEND_PORT
EOF
echo "✅ Created $FRONTEND_ENV"

# Ensure backend/.gitignore exists and includes .env.local
BACKEND_GITIGNORE="$PROJECT_ROOT/backend/.gitignore"
if [[ ! -f "$BACKEND_GITIGNORE" ]] || ! grep -q "\.env\.local" "$BACKEND_GITIGNORE" 2>/dev/null; then
    echo ".env.local" >> "$BACKEND_GITIGNORE"
    echo "✅ Added .env.local to backend/.gitignore"
fi

# frontend/.gitignore already has *.local pattern, but let's verify
FRONTEND_GITIGNORE="$PROJECT_ROOT/frontend/.gitignore"
if [[ -f "$FRONTEND_GITIGNORE" ]] && ! grep -qE "^\*\.local$|\.env\.local" "$FRONTEND_GITIGNORE" 2>/dev/null; then
    echo ".env.local" >> "$FRONTEND_GITIGNORE"
    echo "✅ Added .env.local to frontend/.gitignore"
fi

echo ""
echo "🚀 Development environment configured!"
echo ""
echo "   Backend:  http://localhost:$BACKEND_PORT"
echo "   Frontend: http://localhost:$FRONTEND_PORT"
echo ""
echo "Run ./scripts/dev.sh to start the full stack, or start services individually:"
echo "   Backend:  cd backend && uv run uvicorn app.main:app --reload --port \$PORT"
echo "   Frontend: cd frontend && bun run dev --port \$VITE_PORT"
